const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const path=require('path'),root=path.join(__dirname,'..');
const source=fs.readFileSync(path.join(root,'tavern-ui-bridge.js'),'utf8');
const extract=(start,end)=>source.slice(source.indexOf(start),source.indexOf(end,source.indexOf(start)));
const copy=x=>JSON.parse(JSON.stringify(x));
let owned={dyeTickets:100,cloth0:true,cloth1:true,walletMarker:456},fail=false,calls=0,doll={hair:4,front:0,back:0,cloth:0,face:0};
const ctx={clone:copy,myKey:'test-user',ROOT:'/peiwan',window:{__owned:copy(owned),__ownedParts:()=>({front:{items:[{idx:0}]},back:{items:[{idx:0}]},cloth:{items:[{idx:0}]},face:{items:[{idx:0}]}})},me:()=>({b:{doll}}),HAIRS:Array(10).fill(['#123456']),dollSafe:copy,validPart:r=>r.source==='cloth1'&&['front','back','cloth'].includes(r.slot)?{category:r.slot==='cloth'?'cloth':'hair',slot:r.slot,source:r.source}:null,POSES:[],setFrame(){},drawDollTo(){},db:{ref:p=>({once:async()=>({val:()=>copy(owned)}),transaction:async fn=>{calls++;if(fail)throw Error('模擬連線失敗');const result=fn(copy(owned));if(result!==undefined)owned=copy(result);return {committed:result!==undefined,snapshot:{val:()=>copy(owned)}};},set:async d=>{doll=copy(d)}})}};
vm.createContext(ctx);
vm.runInContext(extract('  function makeDoll(', '  // 這份新穿戴')+extract('  async function wear(', '  window.TinyTavernUI='),ctx);
const selection={front:{source:'cloth1',slot:'front'},back:{base:0,slot:'back'},cloth:{base:0,slot:'cloth'}};
const draft={name:'粉紫漸層',main:'#8A59DA',tail:'#F1B8DE'};
(async()=>{
  const preview=ctx.makeDoll(selection,{},true);assert.equal(owned.dyeTickets,100);assert.equal(calls,0);
  await ctx.saveDye(selection,draft,'dye_request0001');
  assert.equal(owned.dyeTickets,99);assert.equal(owned.walletMarker,456);assert(owned.cloth1);
  assert.equal(owned.dyedHairSets.dye_request0001.main,'#8a59da');
  await ctx.saveDye(selection,draft,'dye_request0001');assert.equal(owned.dyeTickets,99);assert.equal(Object.keys(owned.dyedHairSets).length,1);
  const wearing=ctx.makeDoll(selection,{savedId:'dye_request0001'},true);assert.equal(wearing.hairHex,'#8a59da');assert.equal(wearing.hairHex2,'#f1b8de');
  await ctx.wear(selection,{savedId:'dye_request0001'});await ctx.wear(selection,{savedId:'dye_request0001'});assert.equal(owned.dyeTickets,99);assert.equal(doll.dyedHairSet,'dye_request0001');
  assert.throws(()=>ctx.makeDoll({...selection,front:{base:0,slot:'front'}},{savedId:'dye_request0001'},true),/整組穿戴/);
  await assert.rejects(ctx.saveDye(selection,{...draft,main:'#ffffff'},'dye_request0001'),/資料已變更/);assert.equal(owned.dyeTickets,99);
  await assert.rejects(ctx.saveDye(selection,{...draft,main:'bad'},'dye_request0002'),/有效/);
  const both=await Promise.allSettled([ctx.saveDye(selection,draft,'dye_request0003'),ctx.saveDye(selection,draft,'dye_request0004')]);assert.equal(both.filter(r=>r.status==='fulfilled').length,1);assert.equal(owned.dyeTickets,98);
  fail=true;await assert.rejects(ctx.saveDye(selection,draft,'dye_request0005'),/連線/);assert.equal(owned.dyeTickets,98);assert(!owned.dyedHairSets.dye_request0005);fail=false;
  const old=copy(owned);owned.dyeTickets=0;await assert.rejects(ctx.saveDye(selection,draft,'dye_request0006'),/不足/);assert(!owned.dyedHairSets.dye_request0006);
  owned=old;delete owned.cloth1;await assert.rejects(ctx.saveDye(selection,draft,'dye_request0007'),/尚未取得/);assert.equal(owned.dyeTickets,98);
  ctx.myKey=null;await assert.rejects(ctx.saveDye(selection,draft,'dye_request0008'),/登入/);
  for(const p of ['tavern-ui-bridge.js','tavern-ui/live-wardrobe.js'])new vm.Script(fs.readFileSync(path.join(root,p),'utf8'));
  console.log('PASS: 免費預覽、單次扣券與組合原子保存、相同請求重試不重複扣券、連點防護、0券拒絕、失敗保留券數、未擁有髮型拒絕、組合重穿不扣券、原有道具保留、語法檢查');
})().catch(e=>{console.error(e);process.exitCode=1;});
