/* 素材保持原檔；位移、縮放與組合只在預覽畫布及本機草稿運作。 */
(async()=>{'use strict';const $=id=>document.getElementById(id),clone=v=>JSON.parse(JSON.stringify(v)),key='tt-outfit-studio-v1:'+window.TTStudioOwner;const cfg=await fetch('outfit-studio-catalog.json?v=280').then(r=>{if(!r.ok)throw Error('catalog');return r.json()});const originals=new Map(cfg.packs.flatMap(p=>p.layers.map(l=>[l.id,l]))),images=new Map();let state={selected:cfg.packs[0].id,packs:Object.fromEntries(cfg.packs.map(p=>[p.id,{layers:clone(p.layers),bundles:[]}]))},selected=cfg.packs[0].layers[0].id,pending=null,drag=null,failed=0;const chosen=new Set(originals.keys()),cv=$('canvas'),ctx=cv.getContext('2d');
const dye=window.TTStudioDye,dyeCache=new Map(),isHair=l=>/前髮|後髮/.test(l.name);
const current=()=>state.packs[state.selected],layer=()=>current().layers.find(l=>l.id===selected);const msg=t=>$('status').textContent=t;
function validateLayer(x,id){if(!x||x.id!==id)throw Error('圖層不符');for(const [k,min,max] of [['x',-128,128],['y',-128,128],['scale',25,200],['z',-1000,1000]])if(typeof x[k]!=='number'||!Number.isFinite(x[k])||x[k]<min||x[k]>max)throw Error('圖層數值超出範圍');if(typeof x.visible!=='boolean')throw Error('顯示設定無效');return {...clone(originals.get(id)),x:x.x,y:x.y,scale:x.scale,z:x.z,visible:x.visible,...(isHair(originals.get(id))?{dye:dye.validate(x.dye)}:{})};}
function parse(value){if(value.format!=='tiny-tavern-outfit-studio'||value.version!==1||!value.packs)throw Error('不是套裝調整設定');const next={selected:cfg.packs.some(p=>p.id===value.selected)?value.selected:cfg.packs[0].id,packs:{}};for(const p of cfg.packs){const pack=value.packs[p.id];if(!pack||!Array.isArray(pack.layers)||pack.layers.length!==p.layers.length||!Array.isArray(pack.bundles)||pack.bundles.length>50)throw Error('素材不完整');const layers=p.layers.map(l=>validateLayer(pack.layers.find(x=>x.id===l.id),l.id));const bundles=pack.bundles.map(b=>{if(!b||typeof b.name!=='string'||!b.name.trim()||b.name.length>60||!Array.isArray(b.layers)||!b.layers.length||new Set(b.layers.map(l=>l.id)).size!==b.layers.length)throw Error('套裝組格式無效');return {name:b.name,layers:b.layers.map(l=>{if(!p.layers.some(x=>x.id===l.id))throw Error('套裝組素材不符');return validateLayer(l,l.id);})};});next.packs[p.id]={layers,bundles};}return next;}
function exportData(){return {format:'tiny-tavern-outfit-studio',version:1,sourceVersion:281,reference:{canvasSize:128,positiveX:'right',positiveY:'down',scaleUnit:'percent',higherZ:'front',bodyIncluded:false},selected:state.selected,packs:clone(state.packs)};}
function save(){try{localStorage.setItem(key,JSON.stringify(exportData()));$('saved').textContent='草稿已暫存在這個瀏覽器；完成後請下載設定備份。';}catch{$('saved').textContent='瀏覽器無法暫存，請下載設定保存。';}}
try{const old=localStorage.getItem(key);if(old)state=parse(JSON.parse(old));}catch{msg('舊草稿無法載入，已使用原始素材。');}selected=current().layers[0].id;
async function load(src){return new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>{images.set(src,i);resolve(i)};i.onerror=reject;i.src=src;});}
await Promise.all([...originals.values()].map(l=>load(l.src).catch(()=>failed++)));await load(cfg.body).catch(()=>failed++);$('imageStatus').textContent=failed?'有 '+failed+' 張素材載入失敗，請重新整理。':'原圖 128 × 128；點選圖層後直接拖曳。';
function dyedImage(l){const raw=images.get(l.src);if(!raw||!isHair(l)||!l.dye||l.dye.mode==='original')return raw;const signature=JSON.stringify(l.dye),cached=dyeCache.get(l.id);if(cached?.signature===signature)return cached.canvas;const canvas=document.createElement('canvas');canvas.width=raw.naturalWidth;canvas.height=raw.naturalHeight;const c=canvas.getContext('2d');c.drawImage(raw,0,0);const p=c.getImageData(0,0,canvas.width,canvas.height);dye.pixels(p.data,canvas.width,canvas.height,l.dye);c.putImageData(p,0,0);dyeCache.set(l.id,{signature,canvas});return canvas;}
function drawLayer(c,l,origin){const image=dyedImage(l);if(!image)return;const size=128*l.scale/100;c.drawImage(image,origin+64-size/2+l.x,origin+64-size/2+l.y,size,size);}
function draw(){pending=null;ctx.clearRect(0,0,256,256);ctx.imageSmoothingEnabled=false;const ls=current().layers.filter(l=>l.visible).slice();if($('body').checked)ls.push({id:'body',src:cfg.body,x:0,y:0,scale:100,z:15,visible:true});ls.sort((a,b)=>a.z-b.z).forEach(l=>drawLayer(ctx,l,64));if($('guides').checked){ctx.strokeStyle='#ac7c9780';ctx.lineWidth=.5;ctx.setLineDash([2,2]);ctx.strokeRect(64,64,128,128);ctx.beginPath();ctx.moveTo(128,45);ctx.lineTo(128,211);ctx.moveTo(45,128);ctx.lineTo(211,128);ctx.stroke();ctx.setLineDash([]);const l=layer();if(l?.visible){const size=128*l.scale/100;ctx.strokeStyle='#9b4978';ctx.strokeRect(128-size/2+l.x,128-size/2+l.y,size,size);}}}
function queue(){if(pending===null)pending=requestAnimationFrame(draw);}
function valueChange(k,v){const l=layer(),bounds={x:[-128,128],y:[-128,128],scale:[25,200]};if(!Number.isFinite(v))return;l[k]=Math.round(Math.max(bounds[k][0],Math.min(bounds[k][1],v))*2)/2;for(const e of document.querySelectorAll('[data-field="'+k+'"]'))e.value=l[k];save();queue();}
function fields(){const l=layer();dyeFields();$('layerName').textContent=l.name;$('fields').replaceChildren();for(const [k,name,min,max,step] of [['x','左右位置',-128,128,.5],['y','上下位置',-128,128,.5],['scale','大小（%）',25,200,1]]){const box=document.createElement('label');box.className='field';box.append(document.createTextNode(name));for(const type of ['number','range']){const input=document.createElement('input');Object.assign(input,{type,min,max,step,value:l[k]});input.dataset.field=k;input.setAttribute('aria-label',name+(type==='range'?'滑桿':''));input.oninput=()=>{if(input.value!=='')valueChange(k,Number(input.value))};box.append(input);}$('fields').append(box);}}
function layerList(){const list=$('layers');list.replaceChildren();for(const l of current().layers.slice().sort((a,b)=>b.z-a.z)){const box=document.createElement('div');box.className='layer'+(selected===l.id?' active':'');const b=document.createElement('button');b.dataset.layer=l.id;b.setAttribute('aria-pressed',String(selected===l.id));const img=document.createElement('img');img.src=l.src;img.alt='';b.append(img,document.createTextNode(l.name));b.onclick=()=>{selected=l.id;layerList();fields();queue()};box.append(b);for(const [name,checked,change] of [['顯示',l.visible,v=>{l.visible=v;save();queue()}],['加入套裝組',chosen.has(l.id),v=>{v?chosen.add(l.id):chosen.delete(l.id)}]]){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=checked;input.setAttribute('aria-label',l.name+' '+name);input.onchange=()=>change(input.checked);label.append(input,document.createTextNode(name));box.append(label);}list.append(box);}}
function bundleList(){$('bundles').replaceChildren();for(const [i,b] of current().bundles.entries()){const box=document.createElement('div');box.className='bundle';const title=document.createElement('strong');title.textContent=b.name+' · '+b.layers.length+' 層';box.append(title,document.createElement('br'));const edit=document.createElement('button');edit.textContent='載入編輯';edit.onclick=()=>{current().layers=current().layers.map(l=>({...l,visible:false}));for(const l of current().layers)chosen.delete(l.id);for(const l of b.layers){const at=current().layers.findIndex(x=>x.id===l.id);current().layers[at]=clone(l);chosen.add(l.id);}$('bundleName').value=b.name;selected=b.layers[0].id;render();save();};const remove=document.createElement('button');remove.textContent='移除組合';remove.onclick=()=>{if(confirm('移除「'+b.name+'」這個草稿組合？原始素材會保留。')){current().bundles.splice(i,1);bundleList();save();}};box.append(edit,remove);$('bundles').append(box);}}
function render(){$('packName').textContent=cfg.packs.find(p=>p.id===state.selected).name;for(const b of $('packs').children)b.setAttribute('aria-pressed',String(b.dataset.pack===state.selected));layerList();fields();bundleList();queue();}
for(const p of cfg.packs){const b=document.createElement('button');b.textContent=p.name;b.dataset.pack=p.id;b.onclick=()=>{state.selected=p.id;selected=current().layers[0].id;$('bundleName').value='';render();save()};$('packs').append(b);}
function reorder(direction){const ls=current().layers.slice().sort((a,b)=>a.z-b.z),i=ls.findIndex(l=>l.id===selected),j=i+direction;if(j<0||j>=ls.length)return;[ls[i].z,ls[j].z]=[ls[j].z,ls[i].z];save();render();}
$('forward').onclick=()=>reorder(1);$('backward').onclick=()=>reorder(-1);$('resetLayer').onclick=()=>{delete layer().dye;Object.assign(layer(),clone(originals.get(selected)));save();render();};$('all').onclick=()=>{current().layers.forEach(l=>chosen.add(l.id));layerList()};$('none').onclick=()=>{current().layers.forEach(l=>chosen.delete(l.id));layerList()};
$('saveBundle').onclick=()=>{const name=$('bundleName').value.trim(),ls=current().layers.filter(l=>chosen.has(l.id));if(!name||!ls.length){msg('請填套裝組名稱，並至少勾選一個圖層。');return;}if(ls.some(l=>!l.visible)){msg('勾選素材中有隱藏圖層，請先顯示或取消勾選。');return;}const b={name,layers:clone(ls)},at=current().bundles.findIndex(b=>b.name===name);if(at>=0){if(!confirm('更新同名套裝組「'+name+'」的設定？'))return;current().bundles[at]=b;}else{if(current().bundles.length>=50){msg('每套最多保存 50 組。');return;}current().bundles.push(b);}bundleList();save();msg('已保存「'+name+'」，尚未上架。');};
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('download').onclick=()=>download(new Blob([JSON.stringify(exportData(),null,2)],{type:'application/json'}),'小小酒館-套裝調整.json');$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(JSON.stringify(exportData(),null,2));msg('設定已複製。');}catch{msg('無法複製，請改用下載全部設定。');}};
$('import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2e6)throw Error('設定檔過大');const next=parse(JSON.parse(await file.text()));state=next;selected=current().layers[0].id;render();save();msg('已載入設定。');}catch(err){msg('載入失敗：'+err.message);}e.target.value='';};
$('png').onclick=()=>{if(failed){msg('素材尚未完整載入，無法匯出。');return;}const ls=current().layers.filter(l=>l.visible);if(!ls.length){msg('請至少顯示一個素材。');return;}const minX=Math.floor(Math.min(0,...ls.map(l=>64-64*l.scale/100+l.x))),minY=Math.floor(Math.min(0,...ls.map(l=>64-64*l.scale/100+l.y))),maxX=Math.ceil(Math.max(128,...ls.map(l=>64+64*l.scale/100+l.x))),maxY=Math.ceil(Math.max(128,...ls.map(l=>64+64*l.scale/100+l.y)));const out=document.createElement('canvas');out.width=maxX-minX;out.height=maxY-minY;const c=out.getContext('2d');c.imageSmoothingEnabled=false;c.translate(-minX,-minY);ls.slice().sort((a,b)=>a.z-b.z).forEach(l=>drawLayer(c,l,0));out.toBlob(blob=>{if(blob)download(blob,state.selected+'-套裝預覽.png')});msg('已匯出透明組合圖；位移過邊界時畫布會自動擴展，請一併下載設定。');};
function dyeFields(){const l=layer();$('hairDye').hidden=!isHair(l);if(!isHair(l))return;const d=l.dye||dye.defaults();for(const [id,k] of [['dyeMode','mode'],['dyeTop','top'],['dyeBottom','bottom'],['dyeAngle','angle'],['dyeStart','start'],['dyeEnd','end']]){$(id).value=d[k];$(id).disabled=k==='mode'?false:d.mode==='original'||(d.mode==='solid'&&['bottom','angle','start','end'].includes(k));}}
for(const [id,k] of [['dyeMode','mode'],['dyeTop','top'],['dyeBottom','bottom'],['dyeAngle','angle'],['dyeStart','start'],['dyeEnd','end']])$(id).oninput=()=>{const l=layer();if(!isHair(l))return;const d={...(l.dye||dye.defaults()),[k]:['angle','start','end'].includes(k)?Number($(id).value):$(id).value};if(d.start>=d.end){if(k==='start')d.end=d.start+1;else d.start=d.end-1;}l.dye=dye.validate(d);dyeFields();save();queue();};
$('dyeAll').onclick=()=>{const d=clone(layer().dye||dye.defaults());current().layers.filter(isHair).forEach(l=>l.dye=clone(d));save();queue();msg('已套用至這套全部頭髮。');};$('dyeReset').onclick=()=>{delete layer().dye;dyeFields();save();queue();};
const size=()=>{cv.style.width=(256*Number($('zoom').value))+'px';cv.style.height=cv.style.width};$('zoom').onchange=size;$('background').onchange=()=>{$('stage').dataset.bg=$('background').value};$('body').onchange=queue;$('guides').onchange=queue;
cv.onpointerdown=e=>{const l=layer();drag={id:e.pointerId,x:e.clientX,y:e.clientY,ox:l.x,oy:l.y};cv.setPointerCapture(e.pointerId);cv.focus()};cv.onpointermove=e=>{if(!drag||drag.id!==e.pointerId)return;const ratio=256/cv.getBoundingClientRect().width;valueChange('x',drag.ox+(e.clientX-drag.x)*ratio);valueChange('y',drag.oy+(e.clientY-drag.y)*ratio)};cv.onpointerup=cv.onpointercancel=()=>{drag=null};cv.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const axis=['ArrowLeft','ArrowRight'].includes(e.key)?'x':'y',d=['ArrowLeft','ArrowUp'].includes(e.key)?-1:1;valueChange(axis,layer()[axis]+d*(e.shiftKey?5:1));};if(innerWidth<620)$('zoom').value='2';size();render();save();
})().catch(()=>{document.getElementById('imageStatus').textContent='調整素材載入失敗，請重新整理。';});
